apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shuffle-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: shuffle-v2
roleRef:
  kind: ClusterRole
  name: shuffle-cluster-role
  apiGroup: rbac.authorization.k8s.io
